### ISSUE TITLE
add style support like ckeditor5 image style

### ISSUE THREAD

**Issue by idonans** [Technologie-Visao/ckeditor5-video#1]
your ckeditor5-video solved my important problem,  thanks a lot.
..... and ...
ckeditor5 image style can config like this
```
image: {
          styles: ["alignLeft", "alignCenter", "alignRight"],
          toolbar: [
            "imageStyle:alignLeft",
            "imageStyle:alignCenter",
            "imageStyle:alignRight",
          ],
        },
```
could you improve then video plugin support 'video styles and toolbar' ?

**Comment by alexdaube** [comment]
@idonans Use v.23.0.0 to get this. Cheers!

**Comment by idonans** [comment]
> @idonans Use v.23.0.0 to get this. Cheers!

@alexdaube  u great
