### ISSUE TITLE
Drag & Drop upload does not work

### ISSUE THREAD

**Issue by GorkemSahin** [Technologie-Visao/ckeditor5-video#18]
First of all, thanks for the great plugin.

When I drag and drop a video file to the editor, I get the error “Can not read property “size” of undefined”. However, uploading a video through the toolbar button works just fine. Could you please help me out with this? I’m using the Video, AutoVideo and VideoUpload plugins.

I also have Image and HTMLEmbed plugins enabled, could they cause an issue with the video plugin? Video and Image uploads share the same custom adapter.

Thanks a lot.

**Comment by alexdaube** [comment]
Hi @GorkemSahin. I don't think having HTMLEmbed and Image should cause any problem as your setup sounds a lot like my own.  

This looks like a bug on the internal file reader. I will try to have a look at it this week if I can find the time. Otherwise, I will definitely check it out this week-end.

Cheers mate!

**Comment by GorkemSahin** [comment]
@alexdaube I debugged the editor and the plugin and found out what was causing it. You don't need to use toArray() function when the argument is already an array. Had to edit the uploadvideocommand.js file and turned
`const files = toArray( options.files ) || toArray( options.file ) ;`
into 
`const files = Array.isArray(options.file) ? options.file : toArray( options.files ) || toArray( options.file ) ;`
which fixed the problem. :)

**Comment by alexdaube** [comment]
Yup, it's exactly the code snippet I had in mind. I'm going to push a hotfix real soon.
